 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
   workflow_dispatch:
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@latest
       - uses: jasineri/gitartwork@latest
         with:
            # Use this username's contribution graph  
            user_name: Farhang
            # Text on contribution graph 
            text: FA
       - uses: jasineri/simple-push-action@v1
